# Generated by Django 3.2.9 on 2021-12-15 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('column_index', models.PositiveSmallIntegerField()),
                ('column_title', models.CharField(max_length=255)),
                ('wip_limit_on', models.BooleanField(default=True)),
                ('wip_limit', models.PositiveSmallIntegerField(default=5)),
                ('board', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='boards.board')),
            ],
            options={
                'ordering': ['board', 'column_index'],
            },
        ),
    ]
