# Generated by Django 3.2.9 on 2021-12-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResetPasswordToken',
            new_name='PasswordRecoveryToken',
        ),
    ]
