# Generated by Django 3.2.9 on 2022-04-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='passwordrecoverytoken',
            name='salt',
        ),
    ]
