# Generated by Django 3.2.9 on 2021-12-15 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmessage',
            name='sender',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardmembership',
            name='board',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='boards.board'),
        ),
        migrations.AddField(
            model_name='boardmembership',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='users',
            field=models.ManyToManyField(related_name='boards', through='boards.BoardMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='boardmembership',
            index=models.Index(fields=['board', 'user'], name='boards_boar_board_i_eb6bf4_idx'),
        ),
        migrations.AddConstraint(
            model_name='boardmembership',
            constraint=models.UniqueConstraint(fields=('board', 'user'), name='unique_member'),
        ),
        migrations.AddConstraint(
            model_name='boardmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 1)), fields=('board', 'role'), name='unique_admin'),
        ),
        migrations.AddConstraint(
            model_name='boardmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('display_name', ''), _negated=True), fields=('board', 'display_name'), name='unique_display_name'),
        ),
    ]
