# Generated by Django 3.2.9 on 2021-12-15 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('columns', '0001_initial'),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('task_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('task_index', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=255)),
                ('board', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards.board')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='columns.column')),
            ],
            options={
                'ordering': ['board', 'column', 'task_index'],
            },
        ),
    ]
