# Generated by Django 3.2.9 on 2021-12-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command', models.CharField(choices=[('read_board', 'Read Board'), ('create_board', 'Create Board'), ('delete_board', 'Delete Board'), ('update_board', 'Update Board'), ('list_boards', 'List Boards'), ('update_board_title', 'Title'), ('create_msg', 'Create Msg'), ('update_msg', 'Update Msg'), ('create_task', 'Create Task'), ('update_task', 'Update Task'), ('move_task', 'Move Task'), ('delete_task', 'Delete Task'), ('create_column', 'Create Column'), ('update_column', 'Update Column'), ('move_column', 'Move Column'), ('delete_column', 'Delete Column'), ('update_member_display_name', 'Display Name'), ('update_member_role', 'Role'), ('join_board', 'Join'), ('remove_member', 'Remove'), ('leave_board', 'Leave'), ('invite_member', 'Invite'), ('no_command', 'No Command')], editable=False, max_length=255, null=True)),
                ('msg', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
