# Generated by Django 3.2.9 on 2021-12-15 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('boards', '0001_initial'),
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='board',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='boards.board'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='task',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='tasks.task'),
        ),
    ]
