# Generated by Django 3.2.9 on 2022-04-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitetoken',
            name='salt',
        ),
    ]
